[package]
name = "make_rand"
version = "0.1.0"
authors = ["elzup <guild0105@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.3"
crate = "0.0.2"
rand = "0.8.5"
regex = "1.9.5"
